# Generated by Django 4.0.4 on 2023-05-30 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('em_web', '0003_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='em_web.department'),
        ),
    ]
