# Generated by Django 4.0.4 on 2023-06-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_web', '0004_alter_employee_dep'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=16, verbose_name='密码')),
            ],
        ),
    ]
