# Generated by Django 4.0.4 on 2023-06-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_web', '0007_interfacecase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacecase',
            name='reparameter',
            field=models.CharField(max_length=300),
        ),
    ]
