# Generated by Django 4.0.4 on 2023-06-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_web', '0008_alter_interfacecase_reparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacecase',
            name='acresult',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
