# Generated by Django 4.0.4 on 2023-06-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_web', '0009_alter_interfacecase_acresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacecase',
            name='parametertype',
            field=models.CharField(max_length=300),
        ),
    ]
