# Generated by Django 4.0.4 on 2023-06-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_web', '0010_alter_interfacecase_parametertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacecase',
            name='parametertype',
            field=models.CharField(max_length=600),
        ),
    ]
